/* Generated By:JavaCC: Do not edit this line. SkanerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SkanerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARROW_RIGHT = 1;
  /** RegularExpression Id. */
  int ARROW_LEFT = 2;
  /** RegularExpression Id. */
  int ARROW_BI = 3;
  /** RegularExpression Id. */
  int DOUBLE_ARROW_RIGHT = 4;
  /** RegularExpression Id. */
  int DOUBLE_ARROW_LEFT = 5;
  /** RegularExpression Id. */
  int DOUBLE_ARROW_BI = 6;
  /** RegularExpression Id. */
  int QUOTE_OPEN = 7;
  /** RegularExpression Id. */
  int QUOTE_CLOSE = 8;
  /** RegularExpression Id. */
  int DASH_SHORT = 9;
  /** RegularExpression Id. */
  int DASH_LONG = 10;
  /** RegularExpression Id. */
  int SYMBOL_COPYRIGHT = 11;
  /** RegularExpression Id. */
  int SYMBOL_TRADEMARK = 12;
  /** RegularExpression Id. */
  int SYMBOL_REGISTERED = 13;
  /** RegularExpression Id. */
  int NUMER = 14;
  /** RegularExpression Id. */
  int WORD = 15;
  /** RegularExpression Id. */
  int ALNUM = 16;
  /** RegularExpression Id. */
  int ENTER = 17;
  /** RegularExpression Id. */
  int NOWALINIA = 18;
  /** RegularExpression Id. */
  int CYFRA = 19;
  /** RegularExpression Id. */
  int LITERA = 20;
  /** RegularExpression Id. */
  int OGONEK = 21;
  /** RegularExpression Id. */
  int MORETHANLITERA = 22;
  /** RegularExpression Id. */
  int HR = 23;
  /** RegularExpression Id. */
  int HEADLINE_END = 24;
  /** RegularExpression Id. */
  int URL = 25;
  /** RegularExpression Id. */
  int DOMENA = 26;
  /** RegularExpression Id. */
  int EMAIL = 27;
  /** RegularExpression Id. */
  int EMAIL_NAZWA = 28;
  /** RegularExpression Id. */
  int LINKO = 29;
  /** RegularExpression Id. */
  int LINKC = 30;
  /** RegularExpression Id. */
  int OBRO = 31;
  /** RegularExpression Id. */
  int OBRC = 32;
  /** RegularExpression Id. */
  int WYMIARY = 33;
  /** RegularExpression Id. */
  int DOUBLE_SPACE = 34;
  /** RegularExpression Id. */
  int BOLD = 35;
  /** RegularExpression Id. */
  int ITALICS = 36;
  /** RegularExpression Id. */
  int UNDERLINE = 37;
  /** RegularExpression Id. */
  int NO_FORMAT = 38;
  /** RegularExpression Id. */
  int MONO = 39;
  /** RegularExpression Id. */
  int SPACE = 40;
  /** RegularExpression Id. */
  int DELO = 41;
  /** RegularExpression Id. */
  int DELC = 42;
  /** RegularExpression Id. */
  int SUPO = 43;
  /** RegularExpression Id. */
  int SUPC = 44;
  /** RegularExpression Id. */
  int SUBO = 45;
  /** RegularExpression Id. */
  int SUBC = 46;
  /** RegularExpression Id. */
  int CODEO = 47;
  /** RegularExpression Id. */
  int CODEC = 48;
  /** RegularExpression Id. */
  int FILEO = 49;
  /** RegularExpression Id. */
  int FILEC = 50;
  /** RegularExpression Id. */
  int NOWIKIO = 51;
  /** RegularExpression Id. */
  int NOWIKIC = 52;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"->\"",
    "\"<-\"",
    "\"<->\"",
    "\"=>\"",
    "\"<=\"",
    "\"<=>\"",
    "\"<<\"",
    "\">>\"",
    "\"--\"",
    "\"---\"",
    "\"(c)\"",
    "\"(tm)\"",
    "\"(r)\"",
    "<NUMER>",
    "<WORD>",
    "<ALNUM>",
    "<ENTER>",
    "\"\\\\\\\\\"",
    "<CYFRA>",
    "<LITERA>",
    "<OGONEK>",
    "<MORETHANLITERA>",
    "<HR>",
    "<HEADLINE_END>",
    "<URL>",
    "<DOMENA>",
    "<EMAIL>",
    "<EMAIL_NAZWA>",
    "\"[[\"",
    "\"]]\"",
    "\"{{\"",
    "\"}}\"",
    "<WYMIARY>",
    "\"  \"",
    "\"**\"",
    "\"//\"",
    "\"__\"",
    "\"%%\"",
    "\"\\\'\\\'\"",
    "\" \"",
    "\"<del>\"",
    "\"</del>\"",
    "\"<sup>\"",
    "\"</sup>\"",
    "\"<sub>\"",
    "\"</sub>\"",
    "\"<code>\"",
    "\"</code>\"",
    "\"<file>\"",
    "\"</file>\"",
    "\"<nowiki>\"",
    "\"</nowiki>\"",
  };

}
