/* Generated By:JavaCC: Do not edit this line. SkanerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SkanerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMER = 1;
  /** RegularExpression Id. */
  int WORD = 2;
  /** RegularExpression Id. */
  int ALNUM = 3;
  /** RegularExpression Id. */
  int ENTER = 4;
  /** RegularExpression Id. */
  int NOWALINIA = 5;
  /** RegularExpression Id. */
  int CYFRA = 6;
  /** RegularExpression Id. */
  int LITERA = 7;
  /** RegularExpression Id. */
  int OGONEK = 8;
  /** RegularExpression Id. */
  int MORETHANLITERA = 9;
  /** RegularExpression Id. */
  int KRESKA = 10;
  /** RegularExpression Id. */
  int HEADLINE = 11;
  /** RegularExpression Id. */
  int URL = 12;
  /** RegularExpression Id. */
  int DOMENA = 13;
  /** RegularExpression Id. */
  int EMAIL = 14;
  /** RegularExpression Id. */
  int EMAIL_NAZWA = 15;
  /** RegularExpression Id. */
  int LINKO = 16;
  /** RegularExpression Id. */
  int LINKC = 17;
  /** RegularExpression Id. */
  int OBRO = 18;
  /** RegularExpression Id. */
  int OBRC = 19;
  /** RegularExpression Id. */
  int WYMIARY = 20;
  /** RegularExpression Id. */
  int DOUBLE_SPACE = 21;
  /** RegularExpression Id. */
  int LISTAN = 22;
  /** RegularExpression Id. */
  int LISTAP = 23;
  /** RegularExpression Id. */
  int BOLD = 24;
  /** RegularExpression Id. */
  int ITALICS = 25;
  /** RegularExpression Id. */
  int UNDERLINE = 26;
  /** RegularExpression Id. */
  int NO_FORMAT = 27;
  /** RegularExpression Id. */
  int MONO = 28;
  /** RegularExpression Id. */
  int SPACE = 29;
  /** RegularExpression Id. */
  int EMOTKA = 30;
  /** RegularExpression Id. */
  int SYMBOL = 31;
  /** RegularExpression Id. */
  int HEADER = 32;
  /** RegularExpression Id. */
  int KOLUMNA = 33;
  /** RegularExpression Id. */
  int VERT_SPAN = 34;
  /** RegularExpression Id. */
  int DIALOG = 35;
  /** RegularExpression Id. */
  int DELO = 36;
  /** RegularExpression Id. */
  int DELC = 37;
  /** RegularExpression Id. */
  int SUPO = 38;
  /** RegularExpression Id. */
  int SUPC = 39;
  /** RegularExpression Id. */
  int SUBO = 40;
  /** RegularExpression Id. */
  int SUBC = 41;
  /** RegularExpression Id. */
  int CODEO = 42;
  /** RegularExpression Id. */
  int CODEC = 43;
  /** RegularExpression Id. */
  int QUOTEO = 44;
  /** RegularExpression Id. */
  int QUOTEC = 45;
  /** RegularExpression Id. */
  int FILEO = 46;
  /** RegularExpression Id. */
  int FILEC = 47;
  /** RegularExpression Id. */
  int NOWIKIO = 48;
  /** RegularExpression Id. */
  int NOWIKIC = 49;
  /** RegularExpression Id. */
  int FOOTNOTEO = 50;
  /** RegularExpression Id. */
  int FOOTNOTEC = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUMER>",
    "<WORD>",
    "<ALNUM>",
    "<ENTER>",
    "\"\\\\\\\\\"",
    "<CYFRA>",
    "<LITERA>",
    "<OGONEK>",
    "<MORETHANLITERA>",
    "<KRESKA>",
    "<HEADLINE>",
    "<URL>",
    "<DOMENA>",
    "<EMAIL>",
    "<EMAIL_NAZWA>",
    "\"[[\"",
    "\"]]\"",
    "\"{{\"",
    "\"}}\"",
    "<WYMIARY>",
    "\"  \"",
    "<LISTAN>",
    "<LISTAP>",
    "\"**\"",
    "\"//\"",
    "\"__\"",
    "\"%%\"",
    "\"\\\'\\\'\"",
    "\" \"",
    "<EMOTKA>",
    "<SYMBOL>",
    "\"^\"",
    "\"|\"",
    "\":::\"",
    "<DIALOG>",
    "\"<del>\"",
    "\"</del>\"",
    "\"<sup>\"",
    "\"</sup>\"",
    "\"<sub>\"",
    "\"</sub>\"",
    "\"<code>\"",
    "\"</code>\"",
    "\"<<\"",
    "\">>\"",
    "\"<file>\"",
    "\"</file>\"",
    "\"<nowiki>\"",
    "\"</nowiki>\"",
    "\"((\"",
    "\"))\"",
  };

}
