/* Generated By:JavaCC: Do not edit this line. SkanerTokenManager.java */

/** Token Manager. */
public class SkanerTokenManager implements SkanerConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x820001f0f0000L) != 0L)
         {
            jjmatchedKind = 9;
            return -1;
         }
         if ((active0 & 0x20200000L) != 0L)
            return 129;
         if ((active0 & 0x20L) != 0L)
         {
            jjmatchedKind = 9;
            return 2;
         }
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 9;
            return 89;
         }
         if ((active0 & 0x4000000000000L) != 0L)
         {
            jjmatchedKind = 9;
            return 79;
         }
         if ((active0 & 0x3dff000000000L) != 0L)
         {
            jjmatchedKind = 9;
            return 74;
         }
         if ((active0 & 0x100000000L) != 0L)
            return 54;
         return -1;
      case 1:
         if ((active0 & 0xaaaa41f0f0000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 9;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x200000L) != 0L)
            return 130;
         if ((active0 & 0x20L) != 0L)
            return 3;
         if ((active0 & 0x1455000000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 9;
               jjmatchedPos = 0;
            }
            return 133;
         }
         return -1;
      case 2:
         if ((active0 & 0x28aa400000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 9;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x1455000000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 9;
               jjmatchedPos = 0;
            }
            return 133;
         }
         return -1;
      case 3:
         if ((active0 & 0x28aa000000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 9;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x1455000000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 9;
               jjmatchedPos = 0;
            }
            return 133;
         }
         return -1;
      case 4:
         if ((active0 & 0x28aa000000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 9;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x1440000000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 9;
               jjmatchedPos = 0;
            }
            return 133;
         }
         return -1;
      case 5:
         if ((active0 & 0x28aa000000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 9;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x1000000000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 9;
               jjmatchedPos = 0;
            }
            return 133;
         }
         return -1;
      case 6:
         if ((active0 & 0x2880000000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 9;
               jjmatchedPos = 0;
            }
            return -1;
         }
         if ((active0 & 0x1000000000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 9;
               jjmatchedPos = 0;
            }
            return 133;
         }
         return -1;
      case 7:
         if ((active0 & 0x2000000000000L) != 0L)
         {
            if (jjmatchedPos == 0)
            {
               jjmatchedKind = 9;
               jjmatchedPos = 0;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 32:
         jjmatchedKind = 29;
         return jjMoveStringLiteralDfa1_0(0x200000L);
      case 37:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 39:
         return jjMoveStringLiteralDfa1_0(0x10000000L);
      case 40:
         return jjMoveStringLiteralDfa1_0(0x4000000000000L);
      case 41:
         return jjMoveStringLiteralDfa1_0(0x8000000000000L);
      case 42:
         return jjMoveStringLiteralDfa1_0(0x1000000L);
      case 47:
         return jjMoveStringLiteralDfa1_0(0x2000000L);
      case 58:
         return jjMoveStringLiteralDfa1_0(0x400000000L);
      case 60:
         return jjMoveStringLiteralDfa1_0(0x3dff000000000L);
      case 62:
         return jjMoveStringLiteralDfa1_0(0x200000000000L);
      case 91:
         return jjMoveStringLiteralDfa1_0(0x10000L);
      case 92:
         return jjMoveStringLiteralDfa1_0(0x20L);
      case 93:
         return jjMoveStringLiteralDfa1_0(0x20000L);
      case 94:
         return jjStartNfaWithStates_0(0, 32, 54);
      case 95:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 123:
         return jjMoveStringLiteralDfa1_0(0x40000L);
      case 124:
         return jjStopAtPos(0, 33);
      case 125:
         return jjMoveStringLiteralDfa1_0(0x80000L);
      default :
         return jjMoveNfa_0(4, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 32:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(1, 21, 130);
         break;
      case 37:
         if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 27);
         break;
      case 39:
         if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(1, 28);
         break;
      case 40:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStopAtPos(1, 50);
         break;
      case 41:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(1, 51);
         break;
      case 42:
         if ((active0 & 0x1000000L) != 0L)
            return jjStopAtPos(1, 24);
         break;
      case 47:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(1, 25);
         return jjMoveStringLiteralDfa2_0(active0, 0x28aa000000000L);
      case 58:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000L);
      case 60:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStopAtPos(1, 44);
         break;
      case 62:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStopAtPos(1, 45);
         break;
      case 91:
         if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(1, 16);
         break;
      case 92:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(1, 5, 3);
         break;
      case 93:
         if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(1, 17);
         break;
      case 95:
         if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(1, 26);
         break;
      case 67:
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x14000000000L);
      case 123:
         if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(1, 18);
         break;
      case 125:
         if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(1, 19);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 58:
         if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(2, 34);
         break;
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x1040000000000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x28000000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x14000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x401000000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x2080000000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x28000000000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(4, 36);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(4, 38);
         else if ((active0 & 0x10000000000L) != 0L)
            return jjStopAtPos(4, 40);
         break;
      case 66:
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa5_0(active0, 0x440000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x802000000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStopAtPos(5, 37);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStopAtPos(5, 39);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(5, 41);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(5, 42);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStopAtPos(5, 46);
         break;
      case 69:
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x880000000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000000L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStopAtPos(6, 43);
         else if ((active0 & 0x800000000000L) != 0L)
            return jjStopAtPos(6, 47);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000000L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStopAtPos(7, 48);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStopAtPos(8, 49);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xb3000000000L, 0x8001000080010L
};
static final long[] jjbitVec1 = {
   0x66000000030000fcL, 0x1e000030cc30001eL, 0x0L, 0x0L
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0x0L, 0x21000000L
};
static final long[] jjbitVec3 = {
   0x400004344100000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec4 = {
   0x400000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec5 = {
   0x0L, 0x0L, 0x0L, 0x2000000000000000L
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 133;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 74:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  else if (curChar == 61)
                     jjCheckNAdd(73);
                  else if (curChar == 45)
                     jjCheckNAdd(73);
                  if (curChar == 61)
                  {
                     if (kind > 31)
                        kind = 31;
                  }
                  else if (curChar == 45)
                  {
                     if (kind > 31)
                        kind = 31;
                  }
                  break;
               case 89:
                  if (curChar == 33)
                     jjCheckNAdd(106);
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 104;
                  else if (curChar == 63)
                     jjCheckNAdd(106);
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 102;
                  if (curChar == 45)
                     jjCheckNAdd(85);
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 99;
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 97;
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 95;
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 93;
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 91;
                  if (curChar == 45)
                     jjCheckNAdd(50);
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 133:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(37, 38);
                  else if (curChar == 46)
                     jjCheckNAdd(34);
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(35, 36);
                  break;
               case 129:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 132;
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 4:
                  if ((0xfc00fffe00000000L & l) != 0L)
                  {
                     if (kind > 9)
                        kind = 9;
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 1)
                        kind = 1;
                     jjCheckNAdd(0);
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 4)
                        kind = 4;
                     jjCheckNAdd(110);
                  }
                  else if (curChar == 32)
                     jjAddStates(4, 5);
                  if (curChar == 61)
                     jjCheckNAddStates(6, 8);
                  else if (curChar == 45)
                     jjCheckNAddStates(9, 12);
                  else if (curChar == 13)
                     jjAddStates(13, 14);
                  else if (curChar == 58)
                     jjAddStates(15, 26);
                  else if (curChar == 56)
                     jjAddStates(27, 28);
                  else if (curChar == 40)
                     jjAddStates(29, 31);
                  else if (curChar == 60)
                     jjCheckNAddStates(32, 35);
                  else if (curChar == 59)
                     jjstateSet[jjnewStateCnt++] = 51;
                  else if (curChar == 63)
                     jjCheckNAdd(47);
                  if (curChar == 60)
                     jjCheckNAdd(34);
                  break;
               case 130:
                  if (curChar == 45)
                  {
                     if (kind > 23)
                        kind = 23;
                  }
                  else if (curChar == 42)
                  {
                     if (kind > 22)
                        kind = 22;
                  }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 1)
                     kind = 1;
                  jjCheckNAdd(0);
                  break;
               case 5:
                  if ((0xfc00fffe00000000L & l) != 0L && kind > 9)
                     kind = 9;
                  break;
               case 6:
                  if (curChar == 46)
                     jjCheckNAdd(7);
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(7, 8);
                  break;
               case 8:
                  if (curChar == 46)
                     jjCheckNAddStates(36, 38);
                  break;
               case 10:
                  if (curChar == 47)
                     jjAddStates(39, 40);
                  break;
               case 12:
                  if (curChar == 46)
                     jjAddStates(41, 42);
                  break;
               case 26:
                  if (curChar == 47)
                     jjCheckNAdd(7);
                  break;
               case 27:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 33:
                  if (curChar == 60)
                     jjCheckNAdd(34);
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(35, 36);
                  break;
               case 36:
                  if (curChar == 46)
                     jjCheckNAdd(34);
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(37, 38);
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(39, 40);
                  break;
               case 40:
                  if (curChar == 46)
                     jjCheckNAddStates(43, 45);
                  break;
               case 42:
                  if (curChar == 62 && kind > 14)
                     kind = 14;
                  break;
               case 46:
                  if (curChar == 63)
                     jjCheckNAdd(47);
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(47, 48);
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 20)
                     kind = 20;
                  jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 50:
                  if (curChar == 41 && kind > 30)
                     kind = 30;
                  break;
               case 51:
               case 84:
                  if (curChar == 45)
                     jjCheckNAdd(50);
                  break;
               case 52:
                  if (curChar == 59)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 71:
                  if (curChar == 60)
                     jjCheckNAddStates(32, 35);
                  break;
               case 72:
                  if (curChar == 45 && kind > 31)
                     kind = 31;
                  break;
               case 73:
                  if (curChar == 62 && kind > 31)
                     kind = 31;
                  break;
               case 75:
                  if (curChar == 61 && kind > 31)
                     kind = 31;
                  break;
               case 76:
                  if (curChar == 61)
                     jjCheckNAdd(73);
                  break;
               case 77:
                  if (curChar == 40)
                     jjAddStates(29, 31);
                  break;
               case 78:
                  if (curChar == 41 && kind > 31)
                     kind = 31;
                  break;
               case 83:
                  if (curChar == 56)
                     jjAddStates(27, 28);
                  break;
               case 86:
                  if (curChar == 45)
                     jjCheckNAdd(85);
                  break;
               case 87:
                  if (curChar == 58)
                     jjAddStates(15, 26);
                  break;
               case 88:
                  if (curChar == 40 && kind > 30)
                     kind = 30;
                  break;
               case 90:
                  if (curChar == 45)
                     jjCheckNAdd(50);
                  break;
               case 91:
                  if (curChar == 47 && kind > 30)
                     kind = 30;
                  break;
               case 92:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 94:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 95:
                  if (curChar == 63 && kind > 30)
                     kind = 30;
                  break;
               case 96:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 98:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 100:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 45)
                     jjCheckNAdd(85);
                  break;
               case 103:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 105:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 106:
                  if (curChar == 58 && kind > 30)
                     kind = 30;
                  break;
               case 107:
                  if (curChar == 63)
                     jjCheckNAdd(106);
                  break;
               case 108:
                  if (curChar == 33)
                     jjCheckNAdd(106);
                  break;
               case 109:
                  if ((0x2400L & l) == 0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  jjCheckNAdd(110);
                  break;
               case 110:
                  if (curChar != 62)
                     break;
                  if (kind > 35)
                     kind = 35;
                  jjCheckNAdd(110);
                  break;
               case 111:
                  if (curChar == 13)
                     jjAddStates(13, 14);
                  break;
               case 112:
                  if (curChar == 10 && kind > 4)
                     kind = 4;
                  break;
               case 113:
                  if (curChar == 10)
                     jjCheckNAdd(110);
                  break;
               case 114:
                  if (curChar == 45)
                     jjCheckNAddStates(9, 12);
                  break;
               case 115:
                  if (curChar == 45)
                     jjCheckNAdd(116);
                  break;
               case 116:
                  if (curChar == 45)
                     jjCheckNAddStates(46, 48);
                  break;
               case 117:
                  if ((0x2400L & l) != 0L && kind > 10)
                     kind = 10;
                  break;
               case 118:
                  if (curChar == 10 && kind > 10)
                     kind = 10;
                  break;
               case 119:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 121:
                  if (curChar == 45)
                     jjCheckNAdd(72);
                  break;
               case 122:
                  if (curChar == 61)
                     jjCheckNAddStates(6, 8);
                  break;
               case 123:
               case 124:
                  if (curChar == 61)
                     jjCheckNAddStates(49, 51);
                  break;
               case 125:
                  if ((0x2400L & l) != 0L && kind > 11)
                     kind = 11;
                  break;
               case 126:
                  if (curChar == 10 && kind > 11)
                     kind = 11;
                  break;
               case 127:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 32)
                     jjAddStates(4, 5);
                  break;
               case 131:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 132:
                  if (curChar == 45 && kind > 23)
                     kind = 23;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 74:
               case 34:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(0, 3);
                  break;
               case 79:
                  if ((0x4000000040000L & l) != 0L)
                     jjCheckNAdd(78);
                  else if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  else if ((0x800000008L & l) != 0L)
                     jjCheckNAdd(78);
                  break;
               case 133:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(37, 38);
                  else if (curChar == 64)
                     jjCheckNAdd(39);
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(35, 36);
                  break;
               case 4:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 2)
                        kind = 2;
                     jjCheckNAdd(1);
                  }
                  else if ((0x68000001b8000001L & l) != 0L)
                  {
                     if (kind > 9)
                        kind = 9;
                  }
                  else if (curChar == 94)
                     jjstateSet[jjnewStateCnt++] = 54;
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  else if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 62;
                  else if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  else if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  else if ((0x80000000800000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 1:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if (curChar == 92)
                     jjCheckNAdd(3);
                  break;
               case 3:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAdd(3);
                  break;
               case 5:
                  if ((0x68000001b8000001L & l) != 0L && kind > 9)
                     kind = 9;
                  break;
               case 7:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjAddStates(52, 53);
                  break;
               case 9:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAddStates(54, 56);
                  break;
               case 11:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(57, 59);
                  break;
               case 13:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 14:
                  if (curChar == 92)
                     jjCheckNAdd(15);
                  break;
               case 15:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAdd(15);
                  break;
               case 16:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 17:
                  if (curChar == 92)
                     jjCheckNAdd(18);
                  break;
               case 18:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddStates(60, 62);
                  break;
               case 19:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 20:
                  if (curChar == 92)
                     jjCheckNAdd(21);
                  break;
               case 21:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAddStates(63, 65);
                  break;
               case 22:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 23:
                  if ((0x80000000800000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 24:
                  if ((0x80000000800000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if ((0x80000000800000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 29:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 35:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(35, 36);
                  break;
               case 37:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(37, 38);
                  break;
               case 38:
                  if (curChar == 64)
                     jjCheckNAdd(39);
                  break;
               case 39:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(39, 40);
                  break;
               case 41:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(41, 42);
                  break;
               case 43:
                  if (curChar == 92)
                     jjCheckNAdd(44);
                  break;
               case 44:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(44, 42);
                  break;
               case 45:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 48:
                  if ((0x100000001000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 53:
                  if (curChar == 94 && kind > 30)
                     kind = 30;
                  break;
               case 54:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 94)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if ((0x100000001000L & l) != 0L && kind > 30)
                     kind = 30;
                  break;
               case 57:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if ((0x2000000020L & l) != 0L && kind > 30)
                     kind = 30;
                  break;
               case 60:
               case 64:
                  if ((0x200000002000L & l) != 0L)
                     jjCheckNAdd(59);
                  break;
               case 61:
                  if ((0x100000001000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 65:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 80:
                  if ((0x200000002000L & l) != 0L)
                     jjCheckNAdd(78);
                  break;
               case 81:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 82:
                  if ((0x4000000040000L & l) != 0L)
                     jjCheckNAdd(78);
                  break;
               case 85:
                  if ((0x800000008000L & l) != 0L && kind > 30)
                     kind = 30;
                  break;
               case 93:
                  if (curChar == 92 && kind > 30)
                     kind = 30;
                  break;
               case 97:
                  if ((0x1000000010L & l) != 0L && kind > 30)
                     kind = 30;
                  break;
               case 99:
                  if ((0x1000000010000L & l) != 0L && kind > 30)
                     kind = 30;
                  break;
               case 102:
                  if ((0x100000001000000L & l) != 0L && kind > 30)
                     kind = 30;
                  break;
               case 104:
                  if (curChar == 124)
                     kind = 30;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 4:
               case 1:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjCheckNAdd(1);
                  break;
               case 3:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 2)
                     kind = 2;
                  jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 9:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAddStates(54, 56);
                  break;
               case 11:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(57, 59);
                  break;
               case 13:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 18:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(60, 62);
                  break;
               case 21:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjCheckNAddStates(63, 65);
                  break;
               case 41:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(41, 42);
                  break;
               case 44:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(44, 42);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 133 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   35, 36, 37, 38, 129, 131, 123, 50, 73, 120, 73, 72, 121, 112, 113, 89, 
   90, 92, 94, 96, 98, 100, 101, 103, 105, 107, 108, 84, 86, 79, 81, 82, 
   72, 74, 75, 76, 7, 9, 22, 11, 19, 13, 16, 39, 41, 45, 116, 117, 
   119, 124, 125, 127, 7, 8, 9, 10, 12, 10, 11, 12, 10, 18, 12, 21, 
   10, 12, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec0[i2] & l2) != 0L);
      case 1:
         return ((jjbitVec1[i2] & l2) != 0L);
      case 2:
         return ((jjbitVec2[i2] & l2) != 0L);
      case 32:
         return ((jjbitVec3[i2] & l2) != 0L);
      case 33:
         return ((jjbitVec4[i2] & l2) != 0L);
      case 255:
         return ((jjbitVec5[i2] & l2) != 0L);
      default :
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\134\134", null, null, null, null, null, null, 
null, null, null, null, "\133\133", "\135\135", "\173\173", "\175\175", null, 
"\40\40", null, null, "\52\52", "\57\57", "\137\137", "\45\45", "\47\47", "\40", null, 
null, "\136", "\174", "\72\72\72", null, null, null, null, null, null, null, null, 
null, "\74\74", "\76\76", null, null, null, null, "\50\50", "\51\51", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[133];
private final int[] jjstateSet = new int[266];
protected char curChar;
/** Constructor. */
public SkanerTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public SkanerTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 133; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
         matchedToken = jjFillToken();
         return matchedToken;
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
