/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMER = 1;
  /** RegularExpression Id. */
  int WORD = 2;
  /** RegularExpression Id. */
  int ALNUM = 3;
  /** RegularExpression Id. */
  int ENTER = 4;
  /** RegularExpression Id. */
  int NOWALINIA = 5;
  /** RegularExpression Id. */
  int CYFRA = 6;
  /** RegularExpression Id. */
  int LITERA = 7;
  /** RegularExpression Id. */
  int OGONEK = 8;
  /** RegularExpression Id. */
  int MORETHANLITERA = 9;
  /** RegularExpression Id. */
  int EMOTKA = 10;
  /** RegularExpression Id. */
  int KRESKA = 11;
  /** RegularExpression Id. */
  int H1 = 12;
  /** RegularExpression Id. */
  int H2 = 13;
  /** RegularExpression Id. */
  int H3 = 14;
  /** RegularExpression Id. */
  int H4 = 15;
  /** RegularExpression Id. */
  int H5 = 16;
  /** RegularExpression Id. */
  int HC = 17;
  /** RegularExpression Id. */
  int URL = 18;
  /** RegularExpression Id. */
  int DOMENA = 19;
  /** RegularExpression Id. */
  int EMAIL = 20;
  /** RegularExpression Id. */
  int EMAIL_NAZWA = 21;
  /** RegularExpression Id. */
  int LINKO = 22;
  /** RegularExpression Id. */
  int LINKC = 23;
  /** RegularExpression Id. */
  int OBRO = 24;
  /** RegularExpression Id. */
  int OBRC = 25;
  /** RegularExpression Id. */
  int WYMIARY = 26;
  /** RegularExpression Id. */
  int DOUBLE_SPACE = 27;
  /** RegularExpression Id. */
  int DOUBLE_ENTER = 28;
  /** RegularExpression Id. */
  int LISTAN = 29;
  /** RegularExpression Id. */
  int LISTAP = 30;
  /** RegularExpression Id. */
  int BOLD = 31;
  /** RegularExpression Id. */
  int ITALICS = 32;
  /** RegularExpression Id. */
  int UNDERLINE = 33;
  /** RegularExpression Id. */
  int NO_FORMAT = 34;
  /** RegularExpression Id. */
  int MONO = 35;
  /** RegularExpression Id. */
  int SPACE = 36;
  /** RegularExpression Id. */
  int SYMBOL = 37;
  /** RegularExpression Id. */
  int HEADER = 38;
  /** RegularExpression Id. */
  int KOLUMNA = 39;
  /** RegularExpression Id. */
  int VERT_SPAN = 40;
  /** RegularExpression Id. */
  int DELO = 41;
  /** RegularExpression Id. */
  int DELC = 42;
  /** RegularExpression Id. */
  int SUPO = 43;
  /** RegularExpression Id. */
  int SUPC = 44;
  /** RegularExpression Id. */
  int SUBO = 45;
  /** RegularExpression Id. */
  int SUBC = 46;
  /** RegularExpression Id. */
  int CODEO = 47;
  /** RegularExpression Id. */
  int CODEC = 48;
  /** RegularExpression Id. */
  int QUOTE1 = 49;
  /** RegularExpression Id. */
  int QUOTE2 = 50;
  /** RegularExpression Id. */
  int QUOTE3 = 51;
  /** RegularExpression Id. */
  int FILEO = 52;
  /** RegularExpression Id. */
  int FILEC = 53;
  /** RegularExpression Id. */
  int NOWIKIO = 54;
  /** RegularExpression Id. */
  int NOWIKIC = 55;
  /** RegularExpression Id. */
  int FOOTNOTEO = 56;
  /** RegularExpression Id. */
  int FOOTNOTEC = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUMER>",
    "<WORD>",
    "<ALNUM>",
    "<ENTER>",
    "\"\\\\\\\\\"",
    "<CYFRA>",
    "<LITERA>",
    "<OGONEK>",
    "<MORETHANLITERA>",
    "<EMOTKA>",
    "<KRESKA>",
    "<H1>",
    "\"=====\"",
    "\"====\"",
    "\"===\"",
    "\"==\"",
    "<HC>",
    "<URL>",
    "<DOMENA>",
    "<EMAIL>",
    "<EMAIL_NAZWA>",
    "\"[[\"",
    "\"]]\"",
    "\"{{\"",
    "\"}}\"",
    "<WYMIARY>",
    "\"  \"",
    "<DOUBLE_ENTER>",
    "<LISTAN>",
    "<LISTAP>",
    "\"**\"",
    "\"//\"",
    "\"__\"",
    "\"%%\"",
    "\"\\\'\\\'\"",
    "<SPACE>",
    "<SYMBOL>",
    "\"^\"",
    "\"|\"",
    "\":::\"",
    "\"<del>\"",
    "\"</del>\"",
    "\"<sup>\"",
    "\"</sup>\"",
    "\"<sub>\"",
    "\"</sub>\"",
    "\"<code>\"",
    "\"</code>\"",
    "<QUOTE1>",
    "<QUOTE2>",
    "<QUOTE3>",
    "\"<file>\"",
    "\"</file>\"",
    "\"<nowiki>\"",
    "\"</nowiki>\"",
    "\"((\"",
    "\"))\"",
  };

}
